name: Release Mediator Package

on:
  workflow_dispatch:   # Manual trigger
    inputs:
      force-publish:
        description: 'Force publish even if no changes detected'
        required: false
        default: false
        type: boolean

jobs:
  # Check if Mediator package has changes
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      mediator-changed: ${{ steps.final.outputs.mediator }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Detect changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          mediator:
            - 'src/Forma.Mediator/**'
            - 'src/Forma.Core/**'
            - 'Directory.Build.props'
            - 'version.json'
      continue-on-error: true
      
    - name: Fallback change detection
      if: steps.changes.outcome == 'failure'
      id: fallback
      run: |
        echo "Change detection failed, defaulting to publish package"
        echo "mediator=true" >> $GITHUB_OUTPUT
        
    - name: Set final outputs
      id: final
      run: |
        if [ "${{ steps.changes.outcome }}" = "success" ]; then
          echo "mediator=${{ steps.changes.outputs.mediator }}" >> $GITHUB_OUTPUT
        else
          echo "mediator=${{ steps.fallback.outputs.mediator }}" >> $GITHUB_OUTPUT
        fi

  # Publish Forma.Mediator
  publish-mediator:
    needs: detect-changes
    if: needs.detect-changes.outputs.mediator-changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.force-publish == true)
    uses: ./.github/workflows/nuget-publish-reusable.yml
    with:
      project-name: Forma.Mediator
      project-path: src/Forma.Mediator/Forma.Mediator.csproj
      run-tests: true
      test-filter: 'FullyQualifiedName~Forma.Tests.Mediator'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}

  # Summary job
  summary:
    needs: [detect-changes, publish-mediator]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Summary
      run: |
        echo "## Mediator Package Release Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Package | Status | Changed |" >> $GITHUB_STEP_SUMMARY
        echo "|---------|--------|---------|" >> $GITHUB_STEP_SUMMARY
        echo "| Forma.Mediator | ${{ needs.publish-mediator.result || 'skipped' }} | ${{ needs.detect-changes.outputs.mediator-changed }} |" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "**Triggered manually**" >> $GITHUB_STEP_SUMMARY
        fi